
var master_dict = {

    // images are the same for every key, regardless of mode
    images: {
        0: "./img/0.gif",
        1: "./img/1.gif",
        2: "./img/2.gif",
        3: "./img/3.gif",
        4: "./img/4.gif",
        5: "./img/5.gif",
        6: "./img/6.gif",
        7: "./img/7.gif",
        8: "./img/8.gif",
        9: "./img/9.gif",
        A: "./img/A.gif",
        B: "./img/b.gif",
        C: "./img/C.gif",
        D: "./img/D.gif",
        E: "./img/E.gif",
        F: "./img/fire.gif",
        G: "./img/G.gif",
        H: "./img/H.gif",
        I: "./img/i.gif",
        J: "./img/J.gif",
        K: "./img/K.gif",
        L: "./img/L.gif",
        M: "./img/M.gif",
        N: "./img/N.gif",
        O: "./img/O.gif",
        P: "./img/p.gif",
        Q: "./img/Q.gif",
        R: "./img/R.gif",
        S: "./img/squiggle.gif",
        T: "./img/T.gif",
        U: "./img/U.gif",
        V: "./img/V.gif",
        W: "./img/W.gif",
        X: "./img/X.gif",
        Y: "./img/Y.gif",
        Z: "./img/Z.gif"
    },//end images

    drum_kit: {
        0: "./audio/drum_kit/kick/kick08.wav", 
        1: "./audio/drum_kit/kick/kick09.wav", 
        2: "./audio/drum_kit/kick/kick10.wav", 
        3: "./audio/drum_kit/kick/kick11.wav", 
        4: "./audio/drum_kit/kick/kick12.wav", 
        5: "./audio/drum_kit/snare/snare 10.wav", 
        6: "./audio/drum_kit/snare/snare 11.wav", 
        7: "./audio/drum_kit/snare/snare 12.wav", 
        8: "./audio/drum_kit/snare/snare 13.wav", 
        9: "./audio/drum_kit/snare/snare 14.wav", 
        A: "./audio/drum_kit/snare/snare 01.wav", 
        B: "./audio/drum_kit/kick/kick01.wav", 
        C: "./audio/drum_kit/kick/kick02.wav", 
        D: "./audio/drum_kit/snare/snare 02.wav", 
        E: "./audio/drum_kit/hats/hat 01.wav", 
        F: "./audio/drum_kit/snare/snare 03.wav", 
        G: "./audio/drum_kit/snare/snare 04.wav", 
        H: "./audio/drum_kit/snare/snare 05.wav", 
        I: "./audio/drum_kit/hats/hat 02.wav", 
        J: "./audio/drum_kit/snare/snare 06.wav", 
        K: "./audio/drum_kit/snare/snare 07.wav", 
        L: "./audio/drum_kit/snare/snare 08.wav", 
        M: "./audio/drum_kit/kick/kick03.wav", 
        N: "./audio/drum_kit/kick/kick04.wav", 
        O: "./audio/drum_kit/hats/hat 03.wav", 
        P: "./audio/drum_kit/hats/hat 04.wav", 
        Q: "./audio/drum_kit/hats/hat 05.wav", 
        R: "./audio/drum_kit/hats/hat 06.wav", 
        S: "./audio/drum_kit/snare/snare 09.wav", 
        T: "./audio/drum_kit/hats/hat 07.wav", 
        U: "./audio/drum_kit/hats/hat 08.wav", 
        V: "./audio/drum_kit/kick/kick05.wav", 
        W: "./audio/drum_kit/hats/hat 09.wav", 
        X: "./audio/drum_kit/kick/kick06.wav",
        Y: "./audio/drum_kit/hats/hat 10.wav", 
        Z: "./audio/drum_kit/kick/kick07.wav"
    },//end drum_kit

    techno: {
        0: "./audio/techno.k01", 
        1: "./audio/techno.k36", 
        2: "./audio/techno.k02", 
        3: "./audio/techno.k35", 
        4: "./audio/techno.k03", 
        5: "./audio/techno.k34", 
        6: "./audio/techno.k04", 
        7: "./audio/techno.k33", 
        8: "./audio/techno.k05", 
        9: "./audio/techno.k32", 
        A: "./audio/techno.k06", 
        B: "./audio/techno.k31", 
        C: "./audio/techno.k07", 
        D: "./audio/techno.k30", 
        E: "./audio/techno.k08", 
        F: "./audio/techno.k29", 
        G: "./audio/techno.k09", 
        H: "./audio/techno.k28", 
        I: "./audio/techno.k10", 
        J: "./audio/techno.k27", 
        K: "./audio/techno.k11", 
        L: "./audio/techno.k26", 
        M: "./audio/techno.k12", 
        N: "./audio/techno.k25", 
        O: "./audio/techno.k13", 
        P: "./audio/techno.k24", 
        Q: "./audio/techno.k14", 
        R: "./audio/techno.k23", 
        S: "./audio/techno.k15", 
        T: "./audio/techno.k22", 
        U: "./audio/techno.k16", 
        V: "./audio/techno.k21", 
        W: "./audio/techno.k17", 
        X: "./audio/techno.k20", 
        Y: "./audio/techno.k18", 
        Z: "./audio/techno.k19"
    },//end techno

    piano: { 
        // white keys
        A: "./audio/piano/C.wav",
        S: "./audio/piano/D.wav",
        D: "./audio/piano/E.wav",
        F: "./audio/piano/F.wav",
        G: "./audio/piano/G.wav",
        H: "./audio/piano/A.wav",
        J: "./audio/piano/B.wav",

        // black keys 
        W: "./audio/piano/Csharp.wav",
        E: "./audio/piano/Dsharp.wav",
        T: "./audio/piano/Fsharp.wav",
        Y: "./audio/piano/Gsharp.wav",
        U: "./audio/piano/Asharp.wav"
    },//end piano

    // FIXME: add tutorial - should probably just use piano keys
    tutorial: {
        0: "./audio/gameover.wav", 
        1: "./audio/gameover.wav", 
        2: "./audio/gameover.wav", 
        3: "./audio/gameover.wav", 
        4: "./audio/gameover.wav", 
        5: "./audio/gameover.wav", 
        6: "./audio/gameover.wav", 
        7: "./audio/gameover.wav", 
        8: "./audio/gameover.wav", 
        9: "./audio/gameover.wav", 
        A: "./audio/gameover.wav", 
        B: "./audio/gameover.wav", 
        C: "./audio/gameover.wav", 
        D: "./audio/gameover.wav", 
        E: "./audio/gameover.wav", 
        F: "./audio/gameover.wav", 
        G: "./audio/gameover.wav", 
        H: "./audio/gameover.wav", 
        I: "./audio/gameover.wav", 
        J: "./audio/gameover.wav", 
        K: "./audio/gameover.wav", 
        L: "./audio/gameover.wav", 
        M: "./audio/gameover.wav", 
        N: "./audio/gameover.wav", 
        O: "./audio/gameover.wav", 
        P: "./audio/gameover.wav", 
        Q: "./audio/gameover.wav", 
        R: "./audio/gameover.wav", 
        S: "./audio/gameover.wav", 
        T: "./audio/gameover.wav", 
        U: "./audio/gameover.wav", 
        V: "./audio/gameover.wav", 
        W: "./audio/gameover.wav", 
        X: "./audio/gameover.wav", 
        Y: "./audio/gameover.wav", 
        Z: "./audio/gameover.wav"
    },//end tutorial

    // extra sounds -- only used during "random" mode
    extra: {
        0: "./audio/gameover.wav", 
        // 1: "./audio/gameover.wav", 
        // 2: "./audio/gameover.wav", 
        // 3: "./audio/gameover.wav", 
        // 4: "./audio/gameover.wav", 
        // 5: "./audio/gameover.wav", 
        // 6: "./audio/gameover.wav", 
        // 7: "./audio/gameover.wav", 
        // 8: "./audio/gameover.wav", 
        // 9: "./audio/gameover.wav", 
        // A: "./audio/gameover.wav", 
        // B: "./audio/gameover.wav", 
        // C: "./audio/gameover.wav", 
        // D: "./audio/gameover.wav", 
        // E: "./audio/gameover.wav", 
        // F: "./audio/gameover.wav", 
        // G: "./audio/gameover.wav", 
        // H: "./audio/gameover.wav", 
        // I: "./audio/gameover.wav", 
        // J: "./audio/gameover.wav", 
        // K: "./audio/gameover.wav", 
        // L: "./audio/gameover.wav", 
        // M: "./audio/gameover.wav", 
        // N: "./audio/gameover.wav", 
        // O: "./audio/gameover.wav", 
        // P: "./audio/gameover.wav", 
        // Q: "./audio/gameover.wav", 
        // R: "./audio/gameover.wav", 
        // S: "./audio/gameover.wav", 
        // T: "./audio/gameover.wav", 
        // U: "./audio/gameover.wav", 
        // V: "./audio/gameover.wav", 
        // W: "./audio/gameover.wav", 
        // X: "./audio/gameover.wav", 
        // Y: "./audio/gameover.wav", 
        Z: "./audio/gameover.wav"
    }//end extra

}//end master_dict
